version: 2.1

# This is here just to make CircleCI
# happy, but might be useful in the future.
parameters:
  run_downstream_tests:
    type: boolean
    default: false

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH}
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

jobs:
  ubuntu_build:
    description: A template for running BoringSSL tests on x64 Ubuntu Bionic Docker VMs
    parameters:
      LIBOQS_SHARED:
        description: "Build liboqs as a shared library."
        type: boolean
        default: false
      BORINGSSL_SHARED:
        description: "Build BoringSSL as a shared library."
        type: boolean
        default: false
    docker:
      - image: openquantumsafe/ci-ubuntu-focal-x86_64:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
      - run:
          name: Clone liboqs
          command: git clone --branch main --single-branch --depth 1 https://github.com/open-quantum-safe/liboqs.git
      - run:
          name: Build liboqs
          command: mkdir build && cd build && cmake .. -G"Ninja" -DBUILD_SHARED_LIBS=<< parameters.LIBOQS_SHARED >> -DOQS_USE_OPENSSL=OFF -DOQS_BUILD_ONLY_LIB=ON -DCMAKE_INSTALL_PREFIX=../../oqs && ninja install
          working_directory: liboqs
      - run:
          name: Configure BoringSSL
          command: mkdir build && cd build && source ~/.bashrc && cmake -GNinja -DBUILD_SHARED_LIBS=<< parameters.BORINGSSL_SHARED >> -DLIBOQS_SHARED=<< parameters.LIBOQS_SHARED >> .. && cmake -LA ..
      - run:
          name: Build BoringSSL
          # More build processes exhaust memory on CircleCI
          command: ninja -j15
          working_directory: build
      - run:
          name: Run BoringSSL tests
          command: ninja run_tests
          working_directory: build
      - run:
          name: Check that we have the bssl server and client syntax right
          command: python3 oqs_scripts/try_handshake.py

workflows:
  version: 2.1
  build:
    jobs:
      - ubuntu_build:
          name: static_oqs-static_bssl
          context: openquantumsafe
      - ubuntu_build:
          name: shared_oqs-shared_bssl
          context: openquantumsafe
          LIBOQS_SHARED: true
          BORINGSSL_SHARED: true
